import Head from "next/head";
import PageHeader from "../../components/pageHeader/PageHeader";

const Projects = () => {
  return (
    <div>
      <Head>
        <title>Projects — Cheah Park</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <PageHeader
          title="Projects"
          subTitle="Some works that I've experimented and created."
        />
      </main>
    </div>
  );
};

export default Projects;
