export const ratio = { landscape: "landscape", portrait: "portrait" };

export const projectData = [
  {
    id: "p0",
    title: "No Drone Zone",
    url: "http://3.84.254.90/",
    github: "https://github.com/chepark/no-drone-zone",
    techStacks: [
      "TypeScript",
      "React",
      "Node",
      "Express",
      "TailwindCSS",
      "MySQL",
      "AWS-EC2",
      "Jest",
      "React Testing Library",
    ],
    thumbnail: "https://postimg.cc/YLRkVJx1",
    imageRatio: ratio.portrait,
  },
  {
    id: "p1",
    title: "Time Traveler",
    url: "",
    github: "https://github.com/chepark/fullstack-time-traveler",
    techStacks: ["Python", "JavaScript", "CSS", "Flask", "MySQL"],
    thumbnail: "https://postimg.cc/YLRkVJx1",
    imageRatio: ratio.portrait,
  },
  {
    id: "p2",
    title: "Joinerry",
    url: "",
    github: "https://github.com/chepark/full-stack-joinerry",
    techStacks: ["React", "JavaScript", "Node", "Express", "Sass", "MongoDB"],
    thumbnail:
      "https://www.directivegroup.com/wp-content/uploads/2017/03/smile-9047-9380-hd-wallpapers-1.jpg",
    imageRatio: ratio.portrait,
  },
  {
    id: "p3",
    title: "Korean House",
    url: "",
    github: "https://github.com/chepark/korean-house",
    techStacks: ["React", "Firebase", "MUI", "Stripe API"],
    thumbnail: "https://cdn.aadl.com/cover/200/10338860.jpg",
    imageRatio: ratio.portrait,
  },
  {
    id: "p4",
    title: "Light-Dark Mode Calculator",
    url: "https://chepark.github.io/typescript-calc",
    github: "https://github.com/chepark/typescript-calc",
    techStacks: ["TypeScript"],
    thumbnail: "https://cdn.aadl.com/cover/200/10338860.jpg",
    imageRatio: ratio.portrait,
  },
  {
    id: "p5",
    title: "Galleria",
    url: "https://soft-pothos-04baa8.netlify.app",
    github: "https://github.com/chepark/galleria",
    techStacks: ["React", "Sass", "Netlify"],
    thumbnail:
      "https://www.directivegroup.com/wp-content/uploads/2017/03/smile-9047-9380-hd-wallpapers-1.jpg",
    imageRatio: ratio.portrait,
  },
  {
    id: "p6",
    title: "Splitter",
    url: "https://chepark.github.io/splitter/",
    github: "https://github.com/chepark/splitter",
    techStacks: ["HTML", "Sass", "JavaScript"],
    thumbnail:
      "https://www.directivegroup.com/wp-content/uploads/2017/03/smile-9047-9380-hd-wallpapers-1.jpg",
    imageRatio: ratio.portrait,
  },
];
