import Head from "next/head";
import PageHeader from "../components/pageHeader/PageHeader";

const about = () => {
  return (
    <div>
      <Head>
        <title>About — Cheah Park</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <PageHeader
          title="About"
          subTitle="I am a frontend developer and an engineering student."
        />
      </main>
    </div>
  );
};

export default about;
