import Head from "next/head";
import Image from "next/image";
import { list } from "postcss";
import SectionPostList from "../components/home/SectionPostList";
import SectionTitle from "../components/home/SectionTitle";
import PageHeader from "../components/pageHeader/PageHeader";
import { getAllPosts } from "../lib/posts";

export default function Home({ postsMeta }) {
  return (
    <div>
      <Head>
        <title>Cheah Park</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PageHeader
        title="Cheah Park"
        subTitle={`I am a front-end developer and an engineering student.
          Colors and diagrams are my other languages.`}
      />

      <div>
        <SectionTitle section="projects" />
      </div>

      <div>
        <SectionTitle section="blog" />
        <SectionPostList postsMeta={postsMeta} />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = getAllPosts().slice(0, 5);
  const postsMeta = posts.map((post) => post.meta);

  return {
    props: {
      postsMeta,
    },
  };
}
