import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cheah Park</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Test</h1>
      </main>

      <footer></footer>
    </div>
  );
}
