import Head from "next/head";
import Image from "next/image";
import SectionTitle from "../components/home/SectionTitle";
import PageHeader from "../components/pageHeader/PageHeader";
import { getAllPosts } from "../lib/posts";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Cheah Park</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PageHeader
        title="Cheah Park"
        subTitle={`I am a front-end developer and engineering student.
          Colors and diagrams are my other languages.`}
      />

      <div>
        <SectionTitle section="projects" />
      </div>

      <div>
        <SectionTitle section="blog" />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = getAllPosts();

  return {
    props: {
      posts,
    },
  };
}
